name: learnup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: any
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  flutter_svg_provider: ^1.0.7
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^9.0.1
  pinput: ^5.0.0
  sms_autofill: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
    - family: Mona-Sans
      fonts:
        - asset: assets/fonts/MonaSansMedium.ttf
          weight: 500